#!/bin/bash
for i in {1..200}
do
    echo $i >> result
    ../bin/algo-bench $i 100 | grep runtime >> result
done

i=0

cat result | while read y; do
    if [ "$i" -eq 0 ]; then
        i=$((i+1))
        printf "%s" $y | tee -a ../doc/quick.dat ../doc/insert.dat
    elif [ "$i" -eq 1 ]; then
        i=$((i+1))
        num=$(echo $y | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\).*$/\1/g')
        printf "\t%s\n" $num >> ../doc/quick.dat
    elif [ "$i" -eq 2 ]; then
        i=0
        num=$(echo $y | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\).*$/\1/g')
        printf "\t%s\n" $num >> ../doc/insert.dat
    fi
done

rm -f result
